# Generated by Django 2.2.3 on 2019-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_noteelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ggituser',
            name='settings',
            field=models.TextField(blank=True),
        ),
    ]
