# Generated by Django 2.2.3 on 2019-07-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20190726_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
