# Generated by Django 2.2.3 on 2019-07-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
