# Generated by Django 2.2.3 on 2019-07-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_ggituser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
